name: keithhanson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5694632588420063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3cc93'
    - '#809dac'
    - '#000000'
    - '#0000ff'
    - '#5555aa'
  brandStrength: 0.41262242244556546
  lightness: 0.5675314674153924
  saturation: 0.5016714106313884
  rhythmicContrast: 0.14377957535907626
purpose: []
